
---
version: '3'

networks:
  monitoring:
    driver: bridge
    
volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../prometheus-2.41.0.linux-amd64:/config
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/config/prometheus.yml"
    expose:
      - 9090
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - monitoring
    
  web:
    build: .
    ports:
      - "8000:5000"
  redis:
    image: "redis:alpine"
